### ISSUE TITLE
Use with environment variables

### ISSUE THREAD

**Issue by g-wilson** [snicol/shush#3]
It's pretty common for developers to use environment variables to inject secrets, both in development and in production (or production-like) environments. Tools like dotenv and direnv have come up to manage this as a standard interface for config (including secrets).

I think it would be nice if during development, or in less-sensitive environments, as a developer you could use plaintext variables:

`MY_SECRET=lookItsPlainText`

But in a sensitive environment, you could use shush to fetch the plaintext value. To do this with a nice developer experience, how about if there was an environment variable parser which could detect if the value of an env var is a shush key, and load it appropriately:

`MY_SECRET=shush://my-dev-env.some-secret`

In the library, usage might look like:

```go
func main() {
	// create storage and cache providers
	storageProvider := storage.NewPMSKMS(awsSession, "your-kms-key-id-here")
	cacheProvider := cache.NewKeychain(keychain.SecClassGenericPassword, "example-app", "com.example-app.secrets")

	// create a new shush session
	ssh := shush.NewSession(cacheProvider, storageProvider, shush.UpsertVersionReplaceDifferent)

	// load value from environment variable
	someApiKey, err := ssh.Getenv("MY_SECRET")

	// if the value of the env var was not a shush protocol, the plaintext value is returned
	// err is non nil if a shush error was encountered, or the env var was not present or zero-length

	client := someApiClient.New(someApiKey)
}
```

**Comment by snicol** [comment]
Implemented in #4

**Comment by g-wilson** [comment]
Nice - it looks (from my reading) that it will not fall-through to use the environment variables literal value if the value is not a valid shush URI.

So as a developer you have to either always provide it as a shush URI or change your code to conditionally call `ssh.GetenvContext`?

**Comment by snicol** [comment]
Correct, there’s no defaulting in the event it could expose wrong values to the app. If the variable URI is the wrong format, or it can’t find the secret it will error to avoid any confusion in the caller.
